/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nounsDaoInterfacesSol from "./NounsDAOInterfaces.sol";
export type { nounsDaoInterfacesSol };
export type { NounsDAOExecutor } from "./NounsDAOExecutor";
export type { NounsDAOLogicV1 } from "./NounsDAOLogicV1";
export type { NounsDAOProxy } from "./NounsDAOProxy";
