[build]
  command = "pnpm turbo run build"
  publish = "packages/nouns-webapp/dist"

[functions]
  directory = "packages/nouns-bots/src/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
