packages:
  - 'packages/*'

catalogMode: manual

catalog:
  '@wagmi/core': ^2.18.0
  wagmi: ^2.18.0
  '@wagmi/cli': ^2.3.1
  viem: ^2.33.0
  react: ^19.1.0
  react-dom: ^19.1.0
  '@types/react': ^19.1.0
  '@types/react-dom': ^19.1.0
  '@types/node': ^22.15.3
  lucide: ^0.525.0
  'lucide-react': ^0.525.0
  dotenv: ^16.5.0
  '@tanstack/react-query': ^5.85.3
  '@tanstack/query-core': ^5.85.3

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - 'bufferutil'
  - 'core-js'
  - 'core-js-pure'
  - 'esbuild'
  - 'keccak'
  - 'netlify-cli'
  - 'postinstall-postinstall'
  - 'secp256k1'
  - 'sharp'
  - 'unix-dgram'
  - 'unrs-resolver'
  - 'utf-8-validate'
  - 'web3'

overrides:
  wagmi: 2.18.0
  '@wagmi/core': 2.18.0
  viem: 2.33.0

  '@babel/traverse': '>=7.23.2'
  '@openzeppelin/contracts': '4.4.0'
  '@openzeppelin/contracts-upgradeable': '4.4.0'
  '@openzeppelin/hardhat-upgrades': '1.8.2'
  '@openzeppelin/upgrades-core': '1.10.0'
  '@types/node': 'catalog:'
  'async': '>=2.6.4'
  'axios': '>=0.30.0'
  'braces': '>=3.0.3'
  'cross-spawn': '>=7.0.5'
  'ejs': '>=3.1.10'
  'elliptic': '>=6.6.1'
  'esbuild': '>=0.25.0'
  'flat': '>=5.0.1'
  'got': '>=11.8.5'
  'http-cache-semantics': '>=4.1.1'
  'json5': '>=1.0.2'
  'lodash': '>=4.17.21'
  'nanoid': '>=3.3.8 <4'
  'nextra>@theguild/remark-mermaid': 'file:./packages/nouns-docs/lib/remark-mermaid-stub'
  'node-gettext': '>=3.0.0'
  'nth-check': '>=2.0.1'
  'postcss': '>=8.4.31'
  'qs': '>=6.5.3'
  'semver': '>=7.5.2'
  'serialize-javascript': '>=6.0.2'
  'tar': '>=6.2.1'
  'tough-cookie': '>=4.1.3'
  'underscore': '>=1.12.1'
  'ws': '>=7.5.10'
  'yargs-parser': '>=5.0.1'

enablePrePostScripts: true
