packages:
  - 'packages/*'

catalog:
  '@wagmi/core': ^2.18.0
  'wagmi': ^2.16.0
  '@wagmi/cli': ^2.3.1
  'viem': ^2.32.1
  'react': ^19.1.0
  'react-dom': ^19.1.0
  '@types/react': '^19.1.0'
  '@types/react-dom': '^19.1.0'
  '@types/node': '^22.15.3'
  'lucide': ^0.525.0
  'lucide-react': ^0.525.0
